### ISSUE TITLE
Is it really embedded in monaco-editor ?

### ISSUE THREAD

**Issue by npenin** [Microsoft/monaco-json#3] opened 2016-07-04 15:18 UTC
Hi Team,

In the README, it claims this module is built in monaco editor. However, I cannot find it in monaco editor to register my own JsonContrib. Can you please update the documentation ?

Thanks,
Nicolas

**Comment by npenin** [comment] 2016-07-04 15:22
referencing Microsoft/monaco-editor#38

**Comment by aeschli** [comment] 2016-07-13 15:03
duplicate of Microsoft/monaco-editor#38, fixed by publishing the latest monaco-editor to npm.

**Closed by aeschli** 2016-07-13 15:03 UTC
